In [1]:
import numpy as np
scores = np.array([    [85, 90, 78, 92, 88],  
                       [72, 75, 80, 68, 74],   
                       [95, 88, 92, 96, 90],     
                       [60, 65, 70, 58, 62],   
                       [88, 84, 86, 89, 87] ])

In [2]:
#Retrieve the scores of Student 3 for all subjects. 
scores[2]

array([95, 88, 92, 96, 90])

In [3]:
#Retrieve the scores for Subject 2 (column 2) across all students.
scores[:,1]

array([90, 75, 88, 65, 84])

In [8]:
#Extract the scores of the first 3 students for the first 2 subjects
scores[:3,:2]

array([[85, 90],
       [72, 75],
       [95, 88]])

In [9]:
#Extract the scores of the last 2 students for the last 3 subjects.
scores[3:,2:]

array([[70, 58, 62],
       [86, 89, 87]])

In [17]:
#Add 5 bonus marks to all scores. 
scores[:+5]

array([[ 90,  95,  83,  97,  93],
       [ 77,  80,  85,  73,  79],
       [100,  93,  97, 101,  95],
       [ 65,  70,  75,  63,  67],
       [ 93,  89,  91,  94,  92]])

In [22]:
#Subtract 10 marks from scores of Subject 4 for all students.
scores[:,4:]-10

array([[83],
       [69],
       [85],
       [57],
       [82]])

In [27]:
#Calculate the percentage scores of each student assuming each subject is out of 100. 
scores.sum(axis=1)/5

array([91.6, 78.8, 97.2, 68. , 91.8])

In [28]:
#Calculate the average score for each student across all subjects. 
scores.mean(axis=1)

array([91.6, 78.8, 97.2, 68. , 91.8])

In [29]:
#.Find the total marks scored by each student. 
scores.sum(axis=1)

array([458, 394, 486, 340, 459])

In [30]:
#Identify the highest score in the entire array.
np.max(scores)

101

In [31]:
#Determine the average score for each subject. 
scores.mean(axis=0)

array([85. , 85.4, 86.2, 85.6, 85.2])

In [32]:
#Find the student with the lowest average score.
lowest_avg_student = np.argmin(average_scores)
print("Lowest average student : ",lowest_avg_student)

63