In [1]:
#question 1
import numpy as np

In [2]:
l1=[100, 200, 150, 300, 250, 400, 350]
arr=np.array(l1)

In [3]:
type(arr)

numpy.ndarray

In [4]:
# Question 2
import numpy as np
store_1_prices = np.array([10, 20, 30])
store_2_prices = np.array([1, 2, 3])
addition_result = store_1_prices + store_2_prices
multiplication_result = store_1_prices * store_2_prices

# Print the results
print("Element-wise Addition:", addition_result)
print("Element-wise Multiplication:", multiplication_result)

Element-wise Addition: [11 22 33]
Element-wise Multiplication: [10 40 90]


In [5]:
#Question 3
sales_january = np.array([300, 400])
sales_february = np.array([500, 600])

combined_sales = np.append(sales_january, sales_february)
print(combined_sales)

[300 400 500 600]


In [6]:
#Question 4
data = np.array([1, 2, 3, 4, 5, 6])

reshaped_data = data.reshape(2, 3)
print(reshaped_data)

[[1 2 3]
 [4 5 6]]


In [7]:
#Question 5
scores = np.array([[80, 90], [85, 95]])

one_d = scores.ravel()
print(one_d)

[80 90 85 95]
